# Generated by Django 2.2.7 on 2019-12-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolarPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('shape', models.CharField(choices=[('rectangular', 'Rectangular'), ('square', 'Square'), ('triangle', 'Triangle')], max_length=255)),
                ('watt', models.IntegerField(help_text='Amount of electricity it produces in Watts')),
                ('material', models.CharField(choices=[('mono-crystalline', 'Mono-Crystalline'), ('poly-crystalline', 'poly-crystalline'), ('thin-film', 'Thin-Film')], max_length=255)),
                ('width', models.IntegerField(help_text='Width of the panel in mm')),
                ('height', models.IntegerField(help_text='Height of the panel in mm')),
                ('thickness', models.IntegerField(help_text='Thickness of the panel in mm')),
                ('weight', models.IntegerField()),
            ],
        ),
    ]
