# Generated by Django 2.2.7 on 2019-12-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solarpanel',
            options={'verbose_name': 'Solar Panel', 'verbose_name_plural': 'Solar Panels'},
        ),
        migrations.AddField(
            model_name='solarpanel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solarpanel',
            name='material',
            field=models.CharField(choices=[('mono-crystalline', 'Mono-Crystalline'), ('poly-crystalline', 'Poly-crystalline'), ('thin-film', 'Thin-Film')], max_length=255),
        ),
    ]
