# Generated by Django 2.2.7 on 2019-12-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191215_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('voltage', models.IntegerField(help_text='Voltage')),
                ('amper_hours', models.IntegerField(help_text='Amper Hours')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the battery in "dollars.cents"', max_digits=15)),
                ('kind', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Battery',
                'verbose_name_plural': 'Batteries',
            },
        ),
        migrations.AlterField(
            model_name='solarpanel',
            name='height',
            field=models.IntegerField(help_text='Height of the panel in cm'),
        ),
        migrations.AlterField(
            model_name='solarpanel',
            name='thickness',
            field=models.IntegerField(help_text='Thickness of the panel in cm'),
        ),
        migrations.AlterField(
            model_name='solarpanel',
            name='width',
            field=models.IntegerField(help_text='Width of the panel in cm'),
        ),
    ]
