# Generated by Django 2.2.7 on 2019-12-15 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_inverter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solarpanel',
            old_name='watt',
            new_name='watts',
        ),
    ]
