# Generated by Django 2.2.7 on 2019-12-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20191215_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='price',
            field=models.FloatField(help_text='Price of the battery in "dollars.cents"'),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='price',
            field=models.FloatField(help_text='Price in "dollars.cents"'),
        ),
        migrations.AlterField(
            model_name='solarpanel',
            name='price',
            field=models.FloatField(help_text='Price of the panel in "dollars.cents"'),
        ),
    ]
