# Generated by Django 2.2.7 on 2019-12-15 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20191215_1649'),
        ('home', '0007_auto_20191215_1928'),
    ]

    operations = [
    ]
