# Generated by Django 2.2.7 on 2019-12-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_merge_20191215_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='price',
            field=models.FloatField(help_text='Price of the panel in "dollars.cents"'),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='price',
            field=models.FloatField(help_text='Price of the panel in "dollars.cents"'),
        ),
        migrations.AlterField(
            model_name='solarpanel',
            name='price',
            field=models.FloatField(help_text='Price of the panel in "dollars.cents"'),
        ),
    ]
