# Generated by Django 2.2.7 on 2019-12-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20191216_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='type',
            field=models.CharField(choices=[('home', 'Home'), ('commercial', 'Commercial')], default='home', max_length=255),
            preserve_default=False,
        ),
    ]
