# Generated by Django 2.2.7 on 2019-12-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_battery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inverter',
            name='type',
            field=models.CharField(choices=[('home', 'Home'), ('commercial', 'Commercial')], default='home', max_length=255),
            preserve_default=False,
        ),
    ]
